### ISSUE TITLE
Replace html5-lint dependency

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#100]
See #98. The server html5-lint was using has been shut down, so we need to find another way to do HTML validation for the tests.
I am very open to suggestions here!

**Comment by agauniyal** [comment]
https://github.com/yaniswang/HTMLHint ?

**Comment by shakeelmohamed** [comment]
@agauniyal that looks like an awesome project!

**Comment by agauniyal** [comment]
https://github.com/zen-audio-player/zen-audio-player.github.io/pull/114
