### ISSUE TITLE
Enhance the demo link

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#102]
Instead of just a simple anchor link, we can use a button with a font awesome icon. The full list of available icons is [here](http://fontawesome.io/icons/).

For example HTML see how the play/pause button is implemented.

**Comment by Ab1d** [comment]
which icon you prefer?

**Comment by shakeelmohamed** [comment]
I'm open to suggestions, I didn't see an obvious choice

**Comment by Ab1d** [comment]
how about http://fontawesome.io/icon/arrow-right/

**Comment by shakeelmohamed** [comment]
Maybe a mouse pointer? http://fontawesome.io/icon/mouse-pointer/

**Comment by Ab1d** [comment]
![screen shot 2016-01-01 at 3 37 22 pm](https://cloud.githubusercontent.com/assets/3349621/12070488/b8fd6fea-b09d-11e5-9aec-caab63d9b6e0.png)
![screen shot 2016-01-01 at 3 38 20 pm](https://cloud.githubusercontent.com/assets/3349621/12070489/c0068b64-b09d-11e5-8fdf-8019f30514e7.png)

**Comment by shakeelmohamed** [comment]
I like the first one

**Comment by Ab1d** [comment]
test is failing getting this error :  
Demo should play the demo when demo link is clicked:
     AssertionError: No link matching '#demo'
      at Browser.clickLink (node_modules/zombie/lib/index.js:692:7)
      at Context.<anonymous> (test/index.js:108:17)

**Comment by shakeelmohamed** [comment]
I left a comment on #103
