### ISSUE TITLE
Nit with spacing on demo button

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#104]
I think it needs to be outside the #audioplayer div. Want to take this one @Ab1d? :smiley:

**Comment by Ab1d** [comment]
i didn't understood the issue properly, please elaborate.

**Comment by shakeelmohamed** [comment]
Sure, I'd like to have less spacing between the text field and the demo link. I've put a box where the spacing should be removed (first screenshot). But, at the same time, the spacing is perfect for when we're currently playing a video (second screenshot).

I tried doing a quick change, and can't seem to get the demo link to stay centered.


Screenshots:
![capturfiles_2](https://cloud.githubusercontent.com/assets/1480063/12073648/a89d50b2-b0dd-11e5-9e0d-bca673e5d94c.png)
![capturfiles_3](https://cloud.githubusercontent.com/assets/1480063/12073649/a89e0836-b0dd-11e5-8f82-828a5c96fa2d.png)
