### ISSUE TITLE
Simplify all URL parsing code with URI.js

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#110]
This seems like a good library and not too large of a dependency, what do we think? https://github.com/medialize/URI.js

**Comment by monicacheung** [comment]
What other things do you plan on adding besides soundcloud support? Right now, I think it's simple enough to not need something like this.

**Comment by shakeelmohamed** [comment]
Nothing else at the moment, using URI.js might simplify/clean up the code in a few places. This is definitely not a top priority for me

**Comment by shakeelmohamed** [comment]
A better choice for this is [js-url](https://github.com/websanova/js-url) we'll be able to get an object of query args by doing something like `url("?", window.location.href)`

**Comment by rjstires** [comment]
js-url is great for `getYouTubeVideoDescription()` but that's really about it. You could use the URL mutation benefits of URI.js (or similar library) in everything.js where you're mutating the URL.
