### ISSUE TITLE
Add csslint as a pretest command

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#112]
We should be linting our css as well https://github.com/CSSLint/csslint

**Comment by agauniyal** [comment]
Rules? All except OOCSS? https://github.com/CSSLint/csslint/wiki/Rules.

**Comment by shakeelmohamed** [comment]
That sounds good. What can we do about code style? (curly brace position, spacing, etc)

**Comment by agauniyal** [comment]
@shakeelmohamed I'm not aware of such service, however we could run some sort of css-beautify which would format according to specific rules (curly braces, indentation...), irrespective of how a dev codes during the npm test or some other npm command. If someone is familiar with git hooks, they are much more suitable for such task :+1:

**Comment by shakeelmohamed** [comment]
If we could have a pretest script for css style, that would be sufficient for me. We don't need to reformat, just tell the developer when something doesn't conform to our style. I want this for pull requests so they can't be merged until the style is right. To merge to the master branch, the Travis CI run has to pass

**Comment by agauniyal** [comment]
Haha finally found another project to compliment with csslint that would help maintain uniform css style - https://github.com/stylelint/stylelint. Here are the [rules](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md).

**Comment by shakeelmohamed** [comment]
That looks perfect! I'm curious to see what happens if we turn on all the rules

**Comment by agauniyal** [comment]
#118
