### ISSUE TITLE
Single test failing with mocha

### ISSUE THREAD

**Issue by agauniyal** [zen-audio-player/zen-audio-player.github.io#113]
![2016-01-05-130559_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/12109963/4c4b7f46-b3ad-11e5-9a2f-2eeebd62c64e.png)

At line 22: `assert.ok(!e);`

**Comment by agauniyal** [comment]
Also since I'll be adding htmlhint linter support, what rules do you want to support. Rules are here : https://github.com/yaniswang/HTMLHint/wiki/Rules.

**Comment by shakeelmohamed** [comment]
Can you print the error before that assertion?

As for the HTMLHint rules, let's try standard, accessibility & specification. If there are any failures that can be easily corrected, feel free to fix them. Keep us posted, thanks for doing this work!

**Comment by agauniyal** [comment]
Ignore that, went away with removing modules directory and doing npm update again :smile:
