### ISSUE TITLE
Update the search box text to include "search terms" + update screenshot

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#121]
With #120, we have support for proper search just as you'd do on YouTube!

The placeholder text should become something like

    Search, YouTube video ID, or URL

**Comment by monicacheung** [comment]
Do you mean something like the suggested search queries as you type on youtube?

**Comment by shakeelmohamed** [comment]
That would be cool, but I meant just updating the placeholder text for the input

![capturfiles_10](https://cloud.githubusercontent.com/assets/1480063/12215470/e0e53dc8-b672-11e5-96ed-e2ffd4029d5e.png)

**Comment by monicacheung** [comment]
Okay haha. Update this issue and I can do both?

**Comment by shakeelmohamed** [comment]
Let's make them separate issues, I like the idea of keeping "quick fixes" on their own. I've assigned this one to you, feel free to make an issue for the autocomplete feature
