### ISSUE TITLE
CORS issue in OS X Safari

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#125]
I haven't looked into this yet, but it seems like a regression. @monicacheung may have some thoughts

# Clicking the demo button, or trying to submit any videoID/URL

![capturfiles_11](https://cloud.githubusercontent.com/assets/1480063/12218544/3c6e6d36-b6d7-11e5-9e2e-fa2f4d52920c.png)

# Search still works fine though

![capturfiles_12](https://cloud.githubusercontent.com/assets/1480063/12218555/9270d886-b6d7-11e5-9933-4199021d608e.png)

**Comment by monicacheung** [comment]
I can't seem to reproduce this issue. Do you get it 100% of the time?

**Comment by shakeelmohamed** [comment]
Yeah, but I unmuted my speakers and it's actually playing the video in the background :laughing:

**Comment by monicacheung** [comment]
Comment out the ```if (event.target.getPlayerState() !== YT.Player``` block and you will probably see the player. But I think it will break something else. Can you do ```console.log("TEST" + event.target.getPlayerState());``` in this function?

```
function onPlayerReady(event) {
    var currentVideoID = getCurrentVideoID();

    updateTweetMessage();

    // If the video isn't going to play, then return.
    if (event.target.getPlayerState() !== YT.PlayerState.BUFFERING) {
        if (currentVideoID.length > 0) {
            errorMessage.show("Invalid YouTube videoID or URL.");
        }
        return;
    }

    // Setup player
    if (currentVideoID) {
        ZenPlayer.init(currentVideoID);
    }
}
```

**Comment by monicacheung** [comment]
This might be a better check. If it doesn't work, then I have another idea...

```
diff --git a/js/everything.js b/js/everything.js
index d47aeed..f618bf0 100644
--- a/js/everything.js
+++ b/js/everything.js
@@ -74,7 +74,7 @@ function onPlayerReady(event) {
     updateTweetMessage();
 
     // If the video isn't going to play, then return.
-    if (event.target.getPlayerState() !== YT.PlayerState.BUFFERING) {
+    if (event.target.getDuration() === 0) {
         if (currentVideoID.length > 0) {
             errorMessage.show("Invalid YouTube videoID or URL.");
         }
```

**Comment by shakeelmohamed** [comment]
Great, I will look at it this week it may be related to #38 (at least on OS X). I think we'll need to add some kind of notice for mobile users saying we don't support mobile browsers

**Comment by shakeelmohamed** [comment]
I totally forgot about this!
This patch works for regular playback, but not for search (we still see the error box)

```diff
diff --git a/js/everything.js b/js/everything.js
index 75fa129..ea4cace 100644
--- a/js/everything.js
+++ b/js/everything.js
@@ -76,7 +76,7 @@ function onPlayerReady(event) {
     updateTweetMessage();
 
     // If the video isn't going to play, then return.
-    if (event.target.getPlayerState() === YT.PlayerState.UNSTARTED) {
+    if (event.target.getDuration() === 0) {
         errorMessage.show("Invalid YouTube videoID or URL.");
         return;
     }

```

**Comment by shakeelmohamed** [comment]
This is still a bug :sob:

**Comment by shakeelmohamed** [comment]
@monicacheung I think this may only happen when running the site locally. I see all the console errors, but everything works as expected...

**Comment by monicacheung** [comment]
We can close this if you don't think it's a problem? I haven't been able to see this problem at all.

**Comment by shakeelmohamed** [comment]
No idea :smiley:
