### ISSUE TITLE
Get slider tooltips working

### ISSUE THREAD

**Issue by eirism** [zen-audio-player/zen-audio-player.github.io#131]
Slider tooltips are currently not working. bootstrap-slider.js uses the tooltip CSS class from bootstrap to get the proper behavior, and as we are currently not including bootstrap the tooltips are broken.

The two ways to fix this, as I see it, is to either include bootstrap in its whole, or to just use the relevant CSS rules from it.

**Comment by shakeelmohamed** [comment]
The main reason we want tooltips is for the the time seek slider to mimic the design used by YouTube:

![](https://cloud.githubusercontent.com/assets/1480063/12273295/f9ceba18-b919-11e5-9bb7-df12b74ac58c.png)

**Comment by moen-io** [comment]
Working on adding this in. We only need a couple of css declarations, so there is probably no need to pull all of bootstrap into this. The positioning may need some work, but I don't want too much dead air above the slider. Thoughts?

![image](https://cloud.githubusercontent.com/assets/10991343/12356788/4e80516e-bb9c-11e5-94ea-9c1c9f9ca00d.png)

**Comment by eirism** [comment]
I think the tooltip should be closer to the handle than it is in your screenshot. 

Another comment about your screenshot that might be better fitting in #132, is the time show on the tooltip. The tooltip and the time-display doesn't show the same time.

**Comment by moen-io** [comment]
@eirism Yeah currently the tooltip updates in real time, while the current time polls every 50ms. I haven't looked into that bit yet but it's definitely on the list.

**Comment by shakeelmohamed** [comment]
We won't need to do this if #136 goes in since plyr already has working tooltips for the time seek slider, and I'd argue it's not really important for the volume slider.

I'll leave this issue open until we get plyr working

**Comment by shakeelmohamed** [comment]
We no longer need this since plyr support has been added, check it out!
