### ISSUE TITLE
Google analytics sends events constantly

### ISSUE THREAD

**Issue by moen-io** [zen-audio-player/zen-audio-player.github.io#134]
GA events are sent several times per second as seen here:

![image](https://cloud.githubusercontent.com/assets/10991343/12364865/171afc06-bbc9-11e5-9448-a701652f6b63.png)

The root cause is that analytics are sent every time `parseYoutubeVideoID` is called. As it happens, this occurs every 50ms via `updatePlayerTime` and `storeTime`.

I will be submitting a PR shortly with a proposed solution.

**Comment by shakeelmohamed** [comment]
This is hilarious actually, thanks for looking into it

**Comment by eirism** [comment]
I did also notice this. How often do we need to send GA events? Only on video load, or more often?

**Comment by shakeelmohamed** [comment]
@eirism Right once per video load. I'm open to a refactor of `parseYoutubeVideoID()`. We can pull `videoID` out as a global variable, then in `parseYoutubeVideoID()` check if it it was null and now set to a value, send a ga event.

**Comment by moen-io** [comment]
@eirism @shakeelmohamed Yeah that's pretty much what I've done. It's a bit messy to just add global variables for these things but it is the simplest solution for now. It would be nice if we could refactor the javascript eventually with proper namespaces etc.
