### ISSUE TITLE
Add support for plyr

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#136]
There's a really well designed HTML5 audio player called [audio.js](https://github.com/kolber/audiojs). Are we able to override the default functionality of all the controls to behave like our current controls? I'm also open to alternative libraries - what do we think? @zen-audio-player/contributors 

<img width="481" alt="capturfiles_3" src="https://cloud.githubusercontent.com/assets/1480063/12368125/78b3a7fa-bb9d-11e5-8687-61f0def9cea2.png">

One reason to use this is when #1 (playlists) is resolved, we can have an [awesome UI](http://kolber.github.io/audiojs/demos/test6.html).

<img width="571" alt="capturfiles_2" src="https://cloud.githubusercontent.com/assets/1480063/12368127/7d6fe1fa-bb9d-11e5-953b-88518f57662e.png">

**Comment by agauniyal** [comment]
Latest commit 7af47a1 on Dec 11, 2013
100+ Issues
15 PR's not merged - back from 2012

:open_mouth:

**Comment by shakeelmohamed** [comment]
@agauniyal Yeah, but it works really well! If it works, I'm not concerned about it being maintained

**Comment by shakeelmohamed** [comment]
Here's an alternative:

https://plyr.io/ - https://github.com/selz/plyr
![capturfiles_1](https://cloud.githubusercontent.com/assets/1480063/12374649/eb855f62-bc56-11e5-8bfa-6f8de7ec6753.png)

They actually have a YouTube player that we could use with just 1 line of css (to hide the video).

### After

![capturfiles_2](https://cloud.githubusercontent.com/assets/1480063/12374692/6a1536a8-bc58-11e5-9e79-a877fba6adf7.png)


### Before
![image](https://cloud.githubusercontent.com/assets/1480063/12374690/5952d7da-bc58-11e5-8d2c-6e3cefb0e575.png)

**Comment by monicacheung** [comment]
Plyr looks nice. It says it's customizable too... Who wants to play around with this? :laughing:

**Comment by joshghent** [comment]
I'm looking to contribute to this project so I'll take a look.

**Comment by shakeelmohamed** [comment]
Thanks @joshghent
