### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#142]
From the survey I sent out recently, some people were in favor of using a version number for the website.
As part of the discussion from #137, using bower for the common code will force us to use a version number at least for that module.

------

If we want to implement version number for this repo, we'll need a versioning strategy. We have a few options:

- Every merge to master is a new version
- PRs will have to target a pre-release branch (ie: develop or trunk), then we have to figure out what constitutes a release, how frequently we should release, etc.
- Maintain current workflow of merging every PR to master, then "release" a new version after some amount of time, or by some other criteria

I'm open to a discussion here, but I'm currently not in favor of a version number for the website. How many websites have version numbers? :smiley:

**Comment by justinmao** [comment]
Feels unnecessary. Your target audience is likely to be composed of people who don't care what version the website is, nor would they be interested in looking into previous/upcoming versions, as long as it works. Rather, I think the focus should be on usability/functionality/style.
