### ISSUE TITLE
If searching with a string containing &, the right side will be ignored

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#146]
This is likely happening somewhere in `$("#form").submit()` in `js/everything.js`, possibly more than just 1 place.

A trivial solution could be replace " & " with "and"

**Comment by eirism** [comment]
From my testing it seems to be the parsing of the search query. The regex in https://github.com/zen-audio-player/zen-audio-player.github.io/blob/master/js/everything.js#L415 removes the & (and #) from the text. I think we should encode special characters in the search query to fix this.

While testing this, I discovered another bug. If you search for something that contains a #, the next click on the search or demo button redirects you to a 404 page. You can try clicking on one of the buttons on this page https://zenplayer.audio/?q=dhjkhf%20#%20test

**Comment by shakeelmohamed** [comment]
@eirism throw some tests at this patch, and let me know what you find

```diff
diff --git a/js/everything.js b/js/everything.js
index 273b795..afd1482 100644
--- a/js/everything.js
+++ b/js/everything.js
@@ -449,7 +449,7 @@ function makeSearchURL(searchQuery) {
     // Remove any #s which break functionality
     url = url.replace("#", "");
 
-    return url + "?q=" + searchQuery;
+    return url + "?q=" + encodeURIComponent(searchQuery);
 }
 
 function anchorURLs(text) {
```

**Comment by eirism** [comment]
Both problems seems to be solved with that code change.
