### ISSUE TITLE
Create issue & PR templates

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#151]
https://github.com/blog/2111-issue-and-pull-request-templates

Also do this for the other repos

**Comment by divayprakash** [comment]
@shakeelmohamed If you still need issue and PR templates for the other repos you mentioned, just give me the names and I'll add those too.

**Comment by shakeelmohamed** [comment]
@divayprakash Sure, I don't have an immediate need on the other repos at the moment but I'll let you know when the time comes!
