### ISSUE TITLE
Additions to contributing notes

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#152]
- [x] Add steps for resolving out of sync branches (which ironically, you will need to do for this PR)
- [x] After you've had 1 PR merged, @shakeelmohamed should add you to the organization. Then you can create any issues you work on before you start. Leave a comment when you've started working on an issue, doing so helps avoid duplicate work."

**Comment by divayprakash** [comment]
Working on it!

**Comment by divayprakash** [comment]
To add steps for resolving out of sync branches, I'd like to do the following -
* recommend that any contributors make changes on a separate branch and not try to push to master
* clean up history properly after PR is merged

@shakeelmohamed that okay?

**Comment by shakeelmohamed** [comment]
For out of sync branches, you can just take a screenshot like I did [here](https://github.com/zen-audio-player/zen-audio-player.github.io/pull/155#issuecomment-196088196) and explain how to read the scary looking text.

>recommend that any contributors make changes on a separate branch and not try to push to master

Not really an issue, nobody has permission to push to the master branch of this repo unless all tests pass in a PR, and more importantly only I can approve a merge.

>clean up history properly after PR is merged

I'm not really concerned about the commit history. If we have any new git users, I don't want them to deal with the risks of squashing commits (ie: I don't want them to lose work if they don't do it quite right).

What's your reasoning behind those 2 additions?

**Comment by divayprakash** [comment]
@shakeelmohamed 
* For out of sync branches, are [these](https://help.github.com/articles/syncing-a-fork/) the instructions leading from the screen shot?
* About the first addition I suggested, I understand your point so there is no need for that.
* About the second addition, I suggested that so that we can avoid any issues with that branch later on, such as the out-of-sync issue etc

**Comment by shakeelmohamed** [comment]
1. yes
2. :smile: 
3. I don't think I understand what you're saying, can you think of an example scenario?

**Comment by divayprakash** [comment]
@shakeelmohamed Have a look and tell me what you think.

Regarding
1. Ok.
2. Yeah........sorry, my bad!
3. I'll get back to you.

**Comment by shakeelmohamed** [comment]
Done in #165
