### ISSUE TITLE
Fix tests commented out from redesign

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#164]
We commented out some tests in #155, and need to fix them

**Comment by divayprakash** [comment]
I'd like to work on this but I need a clarification. This basically requires un-commenting tests in the `tests/index.js` file only right?

**Comment by shakeelmohamed** [comment]
@divayprakash that's the first step, you'll need to update those tests since the HTML structure has changed a bit. Let me know if you have any questions around how the selectors work

**Comment by apoorvnandan** [comment]
As per the changes in #155, I changed the commented tests in the following manner:
If the commented test was

`assert.ok(browser.query("header > figure > a > img.logo").src.indexOf("img/zen-audio-player-905.png") !== -1);`

and I saw that the class of header > figure > a > img was changed in #155 from 'logo' to 'img-100' and that `<a href="https://zenplayer.audio/" title="Zen Audio Player">` was changed to `<a href="https://zenplayer.audio/" title="Zen Audio Player" class="zen-logo">` I changed the test to 

`assert.ok(browser.query("header > figure > a.zen-logo > img.img-100").src.indexOf("img/zen-audio-player-905.png") !== -1);`

Also `footer > p` `footer > p ~ p` and `footer > p ~ p ~p` were moved inside `footer > div.color-grey`.

I changed the 6 commented tests in the same manner and un-commented them.
Does this correctly fix them?

I have sent a pull request containing these changes.
