### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#167]
Thanks to @YuriBrunetto we recently got an awesome redesign! We need an updated screenshot for the README :tada:

**Comment by YuriBrunetto** [comment]
What if we use a mockup? It'll shows both web and mobile screens

**Comment by shakeelmohamed** [comment]
Why not real screenshots?

**Comment by YuriBrunetto** [comment]
What I mean was: using **real** screenshots in a mockup. :smile:

**Comment by shakeelmohamed** [comment]
Go for it
