### ISSUE TITLE
Add npm start command to spin up a web server

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#170]
I've been meaning to create this work item for a while... We have some features that require the site to be run on a web server due to API restrictions (YouTube search, getting the video description). The only way to test these properly is to copy everything onto a web server like MAMP or XAMPP, and very inconvenient. At least for me, the only thing slowing me down during development is this awkward copy process.

I'm thinking we using something simple like [express](http://expressjs.com/) and add support for livereload. This way we don't have to kill and re-start the node process every time we want to see changes. I suggest looking at [grunt-express](https://github.com/blai/grunt-express/) and if we can just use that.

**Comment by agauniyal** [comment]
won't headless testing browsers help here? eg phantomjs & [others](https://github.com/dhamaniasad/HeadlessBrowsers)

**Comment by shakeelmohamed** [comment]
@agauniyal You're correct, we actually use [Zombie](http://zombie.js.org/) for headless tests. I'm thinking more about the development workflow of manually testing/using the site to make sure everything works as expected in production.
