### ISSUE TITLE
Remove browserstack logo (new contributors only)

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#172]
#### I'd like a new contributor to do this

Since we're not going to do #71 we don't need to say we're "sponsored by" browserstack.

Done criteria:

- [x] Remove the logo from `index.html`
- [ ] Make sure the design is still responsive, and the previous step didn't have any side effects
- [ ] Update the screenshot/mockup in the README

Focus on the first step, if you run into issues with the others @YuriBrunetto can help out.

**Comment by YuriBrunetto** [comment]
:+1: :smile:

**Comment by guillermohernandez** [comment]
Jumping in on this
