### ISSUE TITLE
Add support for Twitter Cards

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#178]
It would be really nice to show something (not the thumbnail obviously) in a Twitter card when a https://zenplayer.audio link is shared. Can we show the actual player, something like soundcloud? ([example](https://twitter.com/davidguetta/status/522843748066013185))

Need to brainstorm this a bit, but the [docs for Twitter cards are here](https://dev.twitter.com/cards/overview).

**Comment by shakeelmohamed** [comment]
@divayprakash want to look at this?

**Comment by divayprakash** [comment]
Cool feature to add! Soundcloud has done some serious work on theirs and it'd be great if we could come up with something along the same lines.

**Comment by Jago-Kosolosky** [comment]
If I'm not mistaken (first-timer here) we would need a Twitter Player Card (https://dev.twitter.com/cards/types/player). Doesn't look like too much work, but one of the conditions is:

> Ensure all paths are specified as secure (https://)

I guess this would have to be sorted out first?

**Comment by shakeelmohamed** [comment]
@Jago-Kosolosky yeah that looks about right. We have an SSL cert so https://zenplayer.audio works. Do we need to "force" SSL by redirecting http://zenplayer.audio to https://zenplayer.audio? Or, will only the https links trigger the player card?

**Comment by Jago-Kosolosky** [comment]
@shakeelmohamed I think for the Twitter cards we can just use https and it should work. However, I would recommend (no clue how to do this) "forcing" a redirect to https every time for SEO reasons is links start being shared et cetera. Will have a look at the Twitter Player Card asap!

**Comment by shakeelmohamed** [comment]
@Jago-Kosolosky great! I have https forced for my personal website so, I should be able to figure it out here. Thanks for your efforts

**Comment by shakeelmohamed** [comment]
We now default to https!

**Comment by divayprakash** [comment]
@shakeelmohamed Working on this.

**Comment by divayprakash** [comment]
`twitter:site`
The Twitter @username the card should be attributed to. Required for Twitter Card analytics.

@shakeelmohamed What should I put in here?

**Comment by divayprakash** [comment]
@shakeelmohamed Sorry to not be of much help but I'm unable to understand what value to set this to also:

`twitter:player`
HTTPS URL to iframe player. This must be a HTTPS URL which does not generate active mixed content warnings in a web browser

**Comment by shakeelmohamed** [comment]
> twitter:site
The Twitter @username the card should be attributed to. Required for Twitter Card analytics.

If you don't have a twitter account, you an use mine for now `@_shakeel`

> twitter:player
HTTPS URL to iframe player. This must be a HTTPS URL which does not generate active mixed content warnings in a web browser

Ah. Okay so we actually need to create an iframe player that contains just the plyr player. We need to create an HTML page with just the player, and that will be the URL we use for the twitter card. That page will need to include the the plyr JS & CSS 

@divayprakash  If you're up for it, start hacking on this. The outcome should be a new page that just contains a player that plays a youtube video, ie: `https://zenplayer.audio/iframe.html?v=foobar`. Ping me on gitter if you want some additional guidance 😅

**Comment by divayprakash** [comment]
@shakeelmohamed Thanks for the help, I'll get back to you on Gitter if I need anything else.

**Comment by shakeelmohamed** [comment]
See the discussion in #198 to see why this is blocked

**Comment by shakeelmohamed** [comment]
Impossible unless we render HTML `<meta>` tags on the server-side - which isn't possible as long as we're hosted on GitHub pages AFAIK. Thanks to @divayprakash for leading the exploration on this work!
