### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by divayprakash** [zen-audio-player/zen-audio-player.github.io#184]
So I really don't know if this is a bug or its by design, but I tried listening to a video on `zenplayer.audio`  and didn't have any volume! Poked around a bit and found that the last time I'd used YouTube, I had the volume on 'mute' and closed it that way.

**Comment by shakeelmohamed** [comment]
Wow, this is a great bug! Plyr actually has a mute button in the volume controls, that will intuitively solve this problem. Stay tuned for #176 to be merged!

**Comment by shakeelmohamed** [comment]
This is now fixed!
