### ISSUE TITLE
Update primer to version 3.x (new contributors only)

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#189]
We have a dependency on a UI framework called [primer](https://github.com/primer/primer), and we should update to the latest version as we're behind a few versions.

Done criteria:

- [ ] Take a screenshot of the website running locally for you (Once you have [Node.js](https://nodejs.org/) installed, `npm install` then `npm start`)
- [ ] Update primer (we use [bower](http://bower.io/), so you'll need to first change the version in `bower.json` then actually update the dependency). Make sure you're only updating the version of bower
- [ ] Take a screenshot of the website with the new version of bower
- [ ] Commit your changes, and make a pull request including both screenshots.

Happy to answer any questions!

**Comment by divayprakash** [comment]
I'm willing to take this on if its not a problem because of the 'new contributors' thing. Seems people aren't responding because its been 7 days since you put this up. Let me know what you think!

**Comment by shakeelmohamed** [comment]
Thanks, this is low priority so I'm okay with waiting for a new contributor

**Comment by divayprakash** [comment]
No problem!

**Comment by akkatracker** [comment]
I'm new! I'll give it a look, newish to js, thanks for the easy steps!
