### ISSUE TITLE
Add support for linking to a specific time position

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#193]
In YouTube videos, you can set the `t` query string parameter to the number of seconds you want to start the video at. IE: [`https://www.youtube.com/watch?v=koJv-j1usoI&t=30`](https://www.youtube.com/watch?v=koJv-j1usoI&t=30) to start 30 seconds into the video.

General guidance:

* Call `getParameterByName(window.location.href, "t")` to get the value from the query parameter
* Update `window.sessionStorage[videoID]` in `ZenPlayer.init()` with that value, and it should "just work" due to the event listener for `playing`

Done criteria:

- [ ] No change in functionality if the `t` parameter is missing
- [ ] If `t` parameter is present it immediately overrides the value in `window.sessionStorage[videoID]`, and plays without continually trying to seek.

Bonus:

- [ ] Figure out how to update the URL with the updated current time if the `t` parameter is present (without triggering a page reload). To pull this off, you'll likely need to use a hash URL scheme instead of query arguments (ie: `?v=foobar#t123` instead of `?v=foobar&t=123`

**Comment by josephmagee** [comment]
Is this supposed to add an option in the interface where you can select what second to start from? Or only in the case that someone knows the URL? If so, I'd need to know where. I can take a look at this, though. I'm a newbie when it comes to OSS so if you have something with less of a priority I can take that.

**Comment by shakeelmohamed** [comment]
@josephmagee Just in the URL, you can play around with YouTube's `t` query parameter to get a feel for how it should work. Give it a try, I'm happy to help if you need clarification on anything 😄

**Comment by shakeelmohamed** [comment]
@hjh17 I think you can do this 💪
