### ISSUE TITLE
Update the screenshot - plyr support

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#197]
I keep forgetting to do this every time the UI changes 😅 

See #177 for how this works.

cc: @guillermohernandez @YuriBrunetto you folks want to do this since you've done it before ❓

**Comment by guillermohernandez** [comment]
@shakeelmohamed on it

**Comment by shakeelmohamed** [comment]
Done in #205, thanks @YuriBrunetto!
