### ISSUE TITLE
Add support for Soundcloud

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#2]
I've been thinking about how we can implement Soundcloud support as seamlessly as possible. @monicacheung did a ton of great work in getting this process started, but I think the next step is **breaking out Soundcloud support into it's own repo**.
- I've created a new repo: [zen-audio-player/soundcloud](https://github.com/zen-audio-player/soundcloud)
- The beauty of GitHub Pages allows us to have the url https://ZenPlayer.audio/soundcloud, which now has a holding page
- With a dedicated repo, we can create separate JS files for working Soundcloud without worrying about clobbering the YouTube code. (I'm mainly concerned with the hackiness of `wrapParseVideoID()` in `zap-common.js`)
- In this repo, under the search box we can add a set of radio buttons to determine where to route the request (ie: default to YouTube, and have Soundcloud as an option).
- Breaking things out like this will make adding support for other services easier.

---

Options for both playlists, and single tracks would be cool.
- [x] Figure out how to use the soundcloud JS widget API
- [x] Figure out how to dynamically change the soundcloud track
- [x] Add support to the searchbox for a soundcloud URL
- [x] Update `parseYoutubeVideoID()` to have an else if condition for soundcloud URLS
- [x] Rename `parseYoutubeVideoID()` to something more generic, and updated all uses of the function.
- [x] Add support for pulling a soundcloud URL from the URL, ie: `https://zen-audio-player.github.io/?v=https%3A%2F%2Fsoundcloud.com%2Fuser%2Ftrack`)
- [x] Figure out how to hide the player
- [x] Figure out how to hook into the play/pause controls
- [x] Figure out how to hook into the volume controls
- [ ] Set a "mode" for YouTube vs. soundcloud to prevent the play/pause/volume/show/hide controls from affecting the wrong player
- [ ] Test it out on a few browsers

**Comment by shakeelmohamed** [comment]
Test with this: Exclusive TomorrowWorld Mix: Shaq aka DJ Diesel by TomorrowWorld on SoundCloud - Hear the world’s sounds
https://m.soundcloud.com/tomorrowworld/exclusive-tomorrowworld-mix-shaq

**Comment by shakeelmohamed** [comment]
We can add a toggle switch for changing between youtube & soundcloud, [this plugin](https://simontabor.com/labs/toggles/) looks nice. Another interesting feature would be using HTML5 local storage to maintain youtube vs soundcloud

**Comment by monicacheung** [comment]
>Set a "mode" for YouTube vs. soundcloud to prevent the play/pause/volume/show/hide controls from affecting the wrong player

It only makes sense to have one player at any time, so this might not be a problem.

Also consider not loading a player for pages without ```?v=```? Right now youtube player is there but hidden.

**Comment by monicacheung** [comment]
@shakeelmohamed Working on adding Soundcloud support in plyr

**Comment by shakeelmohamed** [comment]
@zen-audio-player/contributors this is up for grabs now. See the work in progress in #216, please work off of that branch

**Comment by shakeelmohamed** [comment]
@zen-audio-player/contributors FYI, I've updated the description of this issue. The goal is to now have a separate repo for Soundcloud.

**Comment by FleetAdmiral** [comment]
I'll take it up, however i'd love it if others could help me out on this too!

**Comment by Etanyauh** [comment]
I wanted to know the status of this issue. Is it still possible to contribute to this issue? I have tried following what has been happening to this issue, but in the end I got nowhere. It seems that there was separate repo but nothing seems to be there. In short, can I work on it?

**Comment by shakeelmohamed** [comment]
@Etanyauh The last time this was in progress was in PR #216, you can use that branch as a starting point but there are several merge conflicts which I haven't resolved.

**Comment by reemtariqq** [comment]
anyone on this ?

**Comment by shakeelmohamed** [comment]
@reemtariqq see my previous comment, there hasn't been any movement on this for quite some time

**Comment by shakeelmohamed** [comment]
It's been nearly 4 years and no one has stepped up to out, so I'm closing this as a "won't fix". 😄
