### ISSUE TITLE
Run csscss on css/styles.css

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#214]
Steps:

* install [csscss](https://github.com/zmoazeni/csscss)
* run `csscss css/styles.css`
* leave a comment below with any warnings
* fix any warnings, or create an issue with the list of warnings

**Comment by rohshar** [comment]
{#audioplayer .plyr__controls} AND {.tt-menu} share 3 declarations
{#audioplayer .plyr__controls}, {.tt-menu} AND {footer} share 3 declarations

I will try to fix the redundancies
