### ISSUE TITLE
Add Thumbnails to List Returned After Search

### ISSUE THREAD

**Issue by artforlife** [zen-audio-player/zen-audio-player.github.io#223]
It seems to me that this would make the app more friendly to the eye. Often, I would like to re-listen to same videos or mixes. I generally recognize them by their thumbnails. 

I could probably implement this feature (just starred your repo, so it may take me some time to get familiar).

**Comment by shakeelmohamed** [comment]
I agree that this makes sense, but does it defeat the purpose of hiding the visuals? I'm open to a pull request, ping me on email or gitter if you need anything 👍

**Comment by artforlife** [comment]
Will do. I am gonna have a look at the code in next couple days.

**Comment by artforlife** [comment]
Sent PR #232 for this. May need some cleaning up.
