### ISSUE TITLE
Video IDs containing - don't parse correctly

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#225]
For video URLs like ` https://www.youtube.com/watch?v=UAWcs5H-qgQ` only `UAWcs5H` is parsed out. The bug is likely somewhere in `js/zap-common.js`.

Also:

* `https://www.youtube.com/watch?v=i-b4wn2TPRI` only `i` is parsed

**Comment by cipher1729** [comment]
Both the above URLs seem to work just fine.  Could you please elaborate on how to reproduce this issue?

**Comment by shakeelmohamed** [comment]
@cipher1729 sure, go to either of these URLs:
* https://zenplayer.audio/?v=https://www.youtube.com/watch?v=UAWcs5H-qgQ
* https://zenplayer.audio/?v=https://www.youtube.com/watch?v=i-b4wn2TPRI

**Comment by cipher1729** [comment]
I've found a fix for it.  I'll create a pull request

**Comment by rjstires** [comment]
This would inherently be addressed by PR #110

**Comment by rjstires** [comment]
Will be closed by #226
