### ISSUE TITLE
Show Track Timemarks If Original Video Has Them in Description

### ISSUE THREAD

**Issue by artforlife** [zen-audio-player/zen-audio-player.github.io#228]
For instance, this video has track names and their start times in its description. It would be neat to show these once the user starts playback of the video.

https://www.youtube.com/watch?v=PEQEOP1zh_c

**Comment by shakeelmohamed** [comment]
Awesome idea!
Look at what we did in `anchorURLs()` in `everything.js`, we basically need to define another regex for replacing timestamps with the timestamped URLs.

Cases:
* hh:mm:ss - 12:34:56
* h:mm:ss - 1:23:45
* mm:ss - 12:34
* m:ss - 1:23 (this will also deal with videos under 1 minute by doing 0:12)

We'll also need to compute the time in seconds from the above possible string formats, the link can be made with `makeListenURL()` - which may or may not need some refactoring.
**We can make a new function that gets called inside `setupVideoDescription()` to do all of this**

**Comment by hogniRunar** [comment]
I´ll send in a pull request for this after the weekend. Got it mostly sorted I think
