### ISSUE TITLE
Hitting Space Bar Makes The Player Screen Scroll

### ISSUE THREAD

**Issue by artforlife** [zen-audio-player/zen-audio-player.github.io#233]
I think we should enable Pause-Play response when hitting the space bar. At the moment, it makes the window scroll to the bottom. 

### Important
Mark with [x] to select. Leave as [ ] to unselect.

### When reporting a bug/issue:
- [ ] Screenshot
- [ ] The browser, browser version and the operating system you're using
- [ ] The behavior you expect to see, and the actual behavior
- [ ] Steps to reproduce the behavior 
- [ ] \(optional) Possible solution/fix/workaround

### When you open an issue for a change/improvement/feature request:
- [ ] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

**Comment by shakeelmohamed** [comment]
Good idea, this should be relatively easy we just need to make sure it's noop if there's no video loaded yet.

Media key support would be ideal but will have to be done through a browser extension, see https://github.com/zen-audio-player/extension-chrome/issues/18

**Comment by sync350** [comment]
I'll go ahead and get working on this if that's okay with you guys. Shouldn't take too long to hack something up.

**Comment by shakeelmohamed** [comment]
Go for it @sync350! Let us know if you need anything

**Comment by artforlife** [comment]
Yes, this would be a great addition!

**Comment by jeanPokou** [comment]
I am working on this issue
