### ISSUE TITLE
Trivial Suggestion:  Return to "Home" when input is deleted

### ISSUE THREAD

**Issue by xianrusso** [zen-audio-player/zen-audio-player.github.io#248]
This is the "Home" I was referring to:
<img width="1440" alt="screen shot 2017-04-21 at 4 58 55 pm" src="https://cloud.githubusercontent.com/assets/22627739/25283410/fc2e38de-26b3-11e7-8d89-be0cdcc121cc.png">

... and when I enter content in the input:
<img width="1552" alt="screen shot 2017-04-21 at 5 01 17 pm" src="https://cloud.githubusercontent.com/assets/22627739/25283469/2f02fba0-26b4-11e7-8ea7-46f0be328754.png">

... and when I delete the content in which I just entered:
<img width="1552" alt="screen shot 2017-04-21 at 5 02 21 pm" src="https://cloud.githubusercontent.com/assets/22627739/25283499/5009586c-26b4-11e7-8cc4-207b2c5e9d6b.png">

the content that was invoked by the search is still there.  I think a return to the "Home" page would be a nice touch when all content is removed from the input, but as aforementioned in the title, is relatively trivial. 

Anyways, I really dig the app!  Let me know what you think!

**Comment by shakeelmohamed** [comment]
@xianrusso that's a great suggestion and pretty easy to implement! Feel free to submit a PR

**Comment by xianrusso** [comment]
@shakeelmohamed Awesome, I'll get started on it!

**Comment by mubaris** [comment]
@xianrusso If you are not working on this, I would like to take this.

CC: @shakeelmohamed

**Comment by shakeelmohamed** [comment]
@mubaris see #249, it's in progress but not complete.

**Comment by shakeelmohamed** [comment]
This was fixed with #257
