### ISSUE TITLE
DISCUSSION: redesign of Zen Audio Player

### ISSUE THREAD

**Issue by YuriBrunetto** [zen-audio-player/zen-audio-player.github.io#252]
# Why?
As a front-end developer who's also a _little bit_ designer, I always try to think in how to make things more beautiful (for me, of course).

## The redesign
So, I've decided to make a redesign - and it's just a start idea for you guys see and tell me what do you think about it. Oh, and I don't think that the current design is bad, is just an idea for improvement. [You can check out the entire album on Imgur here](http://imgur.com/a/af4Ws).

### Home page
![Home page](http://i.imgur.com/HIKXh2K.png)

### Home page with search
![Home page with search](http://i.imgur.com/mgGdU7O.png)

### Demo page
![Demo page](http://i.imgur.com/aWJLmvs.png)

### Demo page with video description
![Demo page with video description](http://i.imgur.com/ZKlIn5D.png)

**Comment by shakeelmohamed** [comment]
Hi @YuriBrunetto these are a great start, thanks so much!

Here's some suggestions:

* If we can make the gradient be the full height of the page let's do that.
* The red/orange backgrounds for buttons, search results & the player seem to clash with the nice gradient background

**Comment by gpigatto** [comment]
Hey @YuriBrunetto great design, but i think that the colors palette should be rethinked. Something more opaque would be a better choice.

**Comment by Sahil624** [comment]
Nice Work @YuriBrunetto.I think you can use material theme maybe materializecss. I think it will go good with it

**Comment by YuriBrunetto** [comment]
@shakeelmohamed so, I guess we can make the gradient with full height and create a ℹ️  button in the right corner which when you click it, it'll show the Zen Player's sponsors 

I agree about the colors, I'll pick something different

**Comment by YuriBrunetto** [comment]
@gpigatto thanks! Yeah, agree. I'll pick something more opaque, indeed

**Comment by parimatrix** [comment]
I would like to contribute to the redesigning too. 
My suggestion would be to include three tabs at the top as a theme selector:
low key data usage efficient version. a gradient based look. a material design based look.
Can I start working towards this too? New to open source. sorry for any basic mistakes.

**Comment by shakeelmohamed** [comment]
@parimatrix go for it! Ping me on gitter if you need anything

**Comment by imnotjohn** [comment]
I am also interested in this...and like the idea of different themes.

**Comment by shakeelmohamed** [comment]
@imnotjohn see #253, there is some work in progress - feel free to start there and submit a new PR

**Comment by jacobkjhan** [comment]
Hey Shakeel! I'm new to contributing and I'd love to work out some of my designing skills. Is this still up for grabs? Thanks!

**Comment by shakeelmohamed** [comment]
@jacobkjhan go for it! Until this issue is closed, it will be up for grabs

**Comment by jacobkjhan** [comment]
@shakeelmohamed I was wondering if this was the kind of look that you would have wanted. Let me know what you think.
<img width="1678" alt="screen shot 2017-09-27 at 11 49 59 am" src="https://user-images.githubusercontent.com/23072695/30923569-34161c42-a37a-11e7-84b0-fe7ea911e427.png">
<img width="1670" alt="screen shot 2017-09-27 at 11 50 06 am" src="https://user-images.githubusercontent.com/23072695/30923568-3414b654-a37a-11e7-8b36-27b62bd679fc.png">

**Comment by shakeelmohamed** [comment]
@jacobkjhan not a bad first cut! I like the rounded design, here's some thoughts:

* can we get the search box rounded on the left side? 
* the yellow is a bit harsh, can we make it a bit lighter or less opaque?
* the anchor text is barely readable with blue on blue, maybe make it light gray or a very light blue?

**Comment by jacobkjhan** [comment]
<img width="1680" alt="screen shot 2017-09-27 at 2 39 28 pm" src="https://user-images.githubusercontent.com/23072695/30931131-b8da23bc-a391-11e7-83b9-627ae16636c8.png">
<img width="1680" alt="screen shot 2017-09-27 at 2 39 45 pm" src="https://user-images.githubusercontent.com/23072695/30931132-b8dcdeb8-a391-11e7-9889-651e663583b1.png">

Here are some screenshots of the updated changes. Let me know if you'd like me to improve anything else!

**Comment by shakeelmohamed** [comment]
The yellow still looks a bit odd, and still can't clearly see the link text. The search box looks much nicer now

**Comment by jacobkjhan** [comment]
Sorry I'm submitting so many versions. Want to make sure that things are the way you want them to be :) Let me know what you think about the darker background.

![screen shot 2017-09-28 at 3 08 49 pm](https://user-images.githubusercontent.com/23072695/30985697-0c6e59f8-a45f-11e7-8f0a-e8323a8d499d.png)
![screen shot 2017-09-28 at 3 08 35 pm](https://user-images.githubusercontent.com/23072695/30985696-0c6e3a72-a45f-11e7-9ee4-1803ecaa6ef4.png)

**Comment by shakeelmohamed** [comment]
@jacobkjhan I love it!

**Comment by jacobkjhan** [comment]
Awesome! I'll make a PR for the changes. I have another question, with how I altered the html, I am no longer passing two tests. One being:  

1) Page Structure should have logo configured correctly:
     TypeError: Cannot read property 'src' of null
     at Context.<anonymous> (test/index.js:73:78)

and the other being: 

2) Page Structure should have expected elements:
     AssertionError [ERR_ASSERTION]: Couldn't find <header><figure>
     at Context.<anonymous> (test/index.js:78:16)

_______________________________________________________________________________________________________

I've noticed that this is because of the DOM traversal that we have set on our front end tests. Should this be something I alter? I just need some advice as to what I can do.

The test cases are:
describe("Page Structure", function () {

    it("should have logo configured correctly", function () {
         assert.equal(browser.query("header > figure > a").href, "https://zenplayer.audio/");
        });

    it("should have expected elements", function () {
        assert.ok(browser.query("header > figure"), "Couldn't find <header><figure>");
        });
    });

_______________________________________________________________________________________________________

What I ended up doing is that I changed some of the specs to inspect any descendant of header to find figure rather than looking for figure as a direct descendant:

describe("Page Structure", function () {
     it("should have logo configured correctly", function () {
          assert.equal(browser.query("header figure > a").href, "https://zenplayer.audio/");
      });

      it("should have expected elements", function () {
          assert.ok(browser.query("header figure"), "Couldn't find <header><figure>");
     });
});

With those changes, I was able to make all the test specs pass. Would it be alright to make a PR with these changes?

Thanks!

**Comment by shakeelmohamed** [comment]
@jacobkjhan sure, those changes to the test code seem reasonable

**Comment by YuriBrunetto** [comment]
Hey guys! So sorry for the delay, I'm working like hell lately.. hahah

Well, I guess I'll create a new branch and then code the new layout version there. What do you think about this, @shakeelmohamed? Then we could see what we can make better, etc. 

Also, it's very nice to see other people helping us out! 

Cheers 🤓

**Comment by shakeelmohamed** [comment]
@YuriBrunetto my attitude is always, go for it!

**Comment by sombek** [comment]
@YuriBrunetto Hey dude.
I would like to contribute to help with coding the new UI. I liked your design.
If there is any way that I could help. Please let me know😁

**Comment by flordeciruela** [comment]
@YuriBrunetto Hello!

The design is improving and can now suggest that a "hide" and "show" speed parameter be applied.
Regards.

**Comment by YuriBrunetto** [comment]
@sombek hey 😄 
Nice! You could transform the design to CSS, if you want to. 😉
