### ISSUE TITLE
While playing a song, hide the "click for demo" button

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#278]
The demo button should only be visible when nothing is playing.
This change should be pretty small in `everything.js`.

<img width="522" alt="capturfiles_2" src="https://user-images.githubusercontent.com/1480063/35668408-419f1722-06e6-11e8-9941-4f2d7fea99b9.png">

**Comment by nilesh2014** [comment]
Hi @shakeelmohamed!
Is demo button allowed below search-results and also in case of any error for searching video?

**Comment by shakeelmohamed** [comment]
@nilesh2014 sure that's reasonable
