### ISSUE TITLE
Clicking show X, then hide X, the button text doesn't change back to show X

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#279]
This should be a pretty simple change to `everything.js`

![zoeyfnr0gv](https://user-images.githubusercontent.com/1480063/35669233-3eda0a08-06e9-11e8-91f5-1a285e3b5ec2.gif)

**Comment by Ma7eer** [comment]
First timer here will try to work on this one!

**Comment by shakeelmohamed** [comment]
Sorry @Ma7eer, somebody beat you to the PR.  Check out #278 for another good first bug
