### ISSUE TITLE
Upgrade zombie to v6

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#293]
We're currently using Zombie 4.x, and need to update to the latest 6.x.

Reproduction Steps:

* run `npm upgrade zombie`
* run `npm test` and see the tests will now fail in a few places, and the process will hang at the end.

How to complete this task:

* Ensure you're running Node.js 8+
* Update the zombie dependency version as shown above
* Consult the [zombie docs](http://zombie.js.org/) to update the tests in `test/index.js` to conform to the latest standards.
* Make a PR! 🎉

**Comment by jkmdev** [comment]
I'd like to take care of this one if it's alright with you.

**Comment by shakeelmohamed** [comment]
@jkmdev thanks, please do!
