### ISSUE TITLE
Trackjs bower dependency creating an error when tests are run

### ISSUE THREAD

**Issue by jkmdev** [zen-audio-player/zen-audio-player.github.io#295]
This issue was discovered when I began work on #293. I was updating Zombie 4.x to Zombie 6.x and making existing tests compatible with the newer Zombie version.

I decided to run the tests before updating the dependency, and realized that there was already some unexpected output. One of the bower dependencies (trackjs) was creating the following error:

![image](https://user-images.githubusercontent.com/19264796/46391000-bcd9dd00-c6a8-11e8-83b9-df280de624ea.png)

When running the tests I was only expecting messages confirming that the tests were passing, however the tests (which all still pass) included a stack trace being printed to the console. 

To reproduce run `npm test` from the root folder.
   
Updating the dependency to its latest version seems to fix the issue. If you think this is a suitable solution then I can create a new pull request with the updated dependency, or maybe include it in my pull request for #293 .

**Comment by jkmdev** [comment]
@shakeelmohamed alright, will do

**Comment by shakeelmohamed** [comment]
Fixed with #296
