### ISSUE TITLE
Add snyk support to CI for dep vulns

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#299]
See docs here: https://snyk.io/docs/ci for `Node.js CI integration`

When ready for a token, I'll send over a patch with the encrypted token in `.travis.yml` for use in CI.

**Comment by sachincool** [comment]
I want to take a try at this one :+1:  :smiley:

**Comment by shakeelmohamed** [comment]
@sachincool awesome, go for it!

**Comment by sachincool** [comment]
I worked my way with Setting repository variables, But I left a comment in the `.travis.yml` incase you want to encrypt your token and add. @shakeelmohamed
