### ISSUE TITLE
Add support for time_continue querystring value

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#301]
`time_continue` should be treated the same as the `t` querystring value.

Example URL format:

`https://www.youtube.com/watch?time_continue=137&v=XYZ`

This format seems to be used with embedded videos.

**Comment by alaajerbi** [comment]
Hi @shakeelmohamed , can I work on it? :wink:

**Comment by shakeelmohamed** [comment]
Go for it @alaajerbi!

**Comment by johnachor** [comment]
@alaajerbi are you still working on this? If it's okay, I'd like to. @shakeelmohamed

**Comment by shakeelmohamed** [comment]
@johnachor feel free to open a PR, @alaajerbi made a PR on their fork but hasn't made a PR here. Not sure what's going on, but this still needs to get done. 

Maybe something for @MisterAwesome23 😉

**Comment by ShivankSahai** [comment]
Hi. I would like to work on this issue. Is this issue still there?

**Comment by shakeelmohamed** [comment]
@ShivankSahai go for it! Not sure why folks have been abandoning this :)
