### ISSUE TITLE
Remove Keen from readme

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#317]
We only have 1 sponsor now, TrackJS - but our readme still mentions and shows a screenshot with Keen.

- [x] Remove Keen from sponsors sections at the bottom of the README (completed by #319)
- [x] Update the screenshot used in the README (completed by #320)

**Comment by woosle1234** [comment]
I'll update it, who are the current project sponsors?

**Comment by woosle1234** [comment]
https://github.com/zen-audio-player/zen-audio-player.github.io/pull/319

please review my pull request if I have solved the issue
