### ISSUE TITLE
Get a cloudflare cert, and a domain name

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#32]
When/if this happens:

- [x] buy domain name
- [x] Create cloudflare account
- [x] Configure DNS
- [x] Setup CNAME file
- [x] Update all URLs in code
- [x] Update the [Chrome Last.fm extension](https://github.com/david-sabata/web-scrobbler) with the new URL - in progress: https://github.com/david-sabata/web-scrobbler/pull/909
- [x] Update the Chrome extension with the new URL - https://github.com/zen-audio-player/extension-chrome/issues/19 
- [x] Update YouTube API key to allow the new domain

**Comment by shakeelmohamed** [comment]
This is basically blocked on me not wanted to buy a domain :smiley:

**Comment by agauniyal** [comment]
Could use https://dns.js.org/ ?

**Comment by shakeelmohamed** [comment]
That's an option, @ecnepsnai mentioned he was looking into buying a domain - if prefer that. especially we want to find non-technical users at some point

**Comment by ecnepsnai** [comment]
We now own zenplayer.audio

**Comment by shakeelmohamed** [comment]
@ecnepsnai Thank you, this is really awesome! Ping me and we can get the DNS configured :smiley:
