### ISSUE TITLE
Sponsors isn't adjusted at 760x800 resolutions.

### ISSUE THREAD

**Issue by abnazhor** [zen-audio-player/zen-audio-player.github.io#335]
Currently sponsors are correctly aligned in all cases except when the resolution is around 760px. It looks something like this:
![imagen](https://user-images.githubusercontent.com/11428398/67528284-611a3180-f6b9-11e9-8723-4d506694157b.png)

**Comment by abnazhor** [comment]
Also, I would love to work on this issue. Can I?

**Comment by shakeelmohamed** [comment]
@abnazhor please go ahead

**Comment by abnazhor** [comment]
@shakeelmohamed Done!

**Comment by shakeelmohamed** [comment]
Closed with #338
