### ISSUE TITLE
Remove CNAME file

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#343]
We need to delete the CNAME file once the domain expires in Jan 2020, the renewal cost went up 10x to $133.70 and I cannot justify paying that much for it.

**Comment by eel87** [comment]
@shakeelmohamed If I understand correctly, do you simply want this file deleted?  I can do that for you!

**Comment by shakeelmohamed** [comment]
@eel87 please do, go for it. I'll just merge it ASAP since the domain expires on Jan 17

**Comment by eel87** [comment]
@shakeelmohamed okay I will submit the PR .  I got this error when testing - I just want to make sure this doesn't matter:
```
 1) Page Structure
       should have expected metadata:

      AssertionError [ERR_ASSERTION]: 'file://c/Bloc/bloc_projects/open_source/zen-audio-player.github.io/index.html' == 'file://C:\\Bloc\\bloc_projects\\open_source\\zen-audio-player.github.io\\index.html'
      + expected - actual

      -file://c/Bloc/bloc_projects/open_source/zen-audio-player.github.io/index.html
      +file://C:\Bloc\bloc_projects\open_source\zen-audio-player.github.io\index.html
```

**Comment by shakeelmohamed** [comment]
@eel87 yeah the tests passed in CI just fine, no need to worry about that windows pathing. Thanks for the PR
