### ISSUE TITLE
The size of the input window and the search button are different at 475x625.

### ISSUE THREAD

**Issue by myungwoo-Y** [zen-audio-player/zen-audio-player.github.io#344]
The size of the input window and the search button are different at 475x625. 
It looks better to align the inputs and buttons.

This is a screenshot about the issue :

![이미지 12](https://user-images.githubusercontent.com/38170596/70851322-03df7700-1ed7-11ea-89fb-ec06ffcd246e.jpg)

**Comment by myungwoo-Y** [comment]
Also, I would love to work on this issue. Can I?

**Comment by shakeelmohamed** [comment]
@myungwoo-Y thanks for the bug report, go ahead and make a PR!

**Comment by myungwoo-Y** [comment]
Thanks for merging!
