### ISSUE TITLE
Add shortcuts for "community favorites"

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#374]
We currently have a "focus" button for binaural beats, we can generalize this concept to include others.

e.g.: Lofi girl, "permalink" to https://www.youtube.com/watch?v=5qap5aO4i9A&ab_channel=LofiGirl

Maybe adding timed sessions as well? e.g.: focus for 30 mins / 60 mins

**Comment by naomiceron** [comment]
Hello! I would like to give this issue a try, could you assign it to me? :)

**Comment by ShivaniG14** [comment]
Hi @shakeelmohamed, Can I work on this issue?

**Comment by shakeelmohamed** [comment]
@ShivaniG14 please proceed

**Comment by ShivaniG14** [comment]
Hi @shakeelmohamed, I have raised a [PR](https://github.com/zen-audio-player/zen-audio-player.github.io/pull/427) please review it
