### ISSUE TITLE
GitHub icon is not centered horizontally

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#382]
An easy fix is to add this CSS rule, there may be a less hacky way though.

```css
.fa-github {
    width: auto;
}
```

See the screenshot from Safari on macOS 11.6
<img width="470" alt="Screen Shot 2021-10-18 at 9 45 02 PM" src="https://user-images.githubusercontent.com/1480063/137845810-b4966199-632d-46a9-ac80-c77b0d6ad9f9.png">

**Comment by shakeelmohamed** [comment]
@Dhruvsinghjadon thanks, assigned

**Comment by anjannair** [comment]
I have finished working on this issue will be putting a PR in a few minutes
