### ISSUE TITLE
Redesign the README.md file

### ISSUE THREAD

**Issue by Akshata-Gunapache** [zen-audio-player/zen-audio-player.github.io#402]
### When you open an issue for a change/improvement/feature request:
- [x] A description of the problem you're trying to solve, including _why_ you think this is a problem
- [ ] If the feature changes current behavior, reasons why your solution is better
- [ ] \(optional) Possible solution/fix/workaround

I would like to modify the readme and make it look prettier and more attractive.

**Comment by Akshata-Gunapache** [comment]
I am an hacktoberfest 2022 participant. Could you please assign this issue to me?

**Comment by shakeelmohamed** [comment]
Closing due to #403 closing
