### ISSUE TITLE
Play pause does not function/has incorrect state on refresh

### ISSUE THREAD

**Issue by BeigeBadger** [zen-audio-player/zen-audio-player.github.io#41]
OS:
Windows 10 Professional

Browsers affected:
Chrome, Firefox (all that I tested)

How to repro:

Method 1
1. Load up the index page
2. Input a video id
3. Hit search.
4. Refresh the page

Method 2
1. Copy the URL from an already loaded page (do steps 1-3 above to get the URL)
2. Paste in a new tab/window.

Expected behaviour:
Pause button to be displayed and function correctly on page load when a video id has already been provided.

Displayed behaviour:
Video will start playing but the controls will still show the play button. - In Firefox hitting play/pause a couple times with get the button into the correct state. In Chrome nothing happens, this may be to do with the console errors about XSS that are coming through though..

**Comment by shakeelmohamed** [comment]
I will test this on my Windows laptop tonight, not an issue in OS X

**Comment by shakeelmohamed** [comment]
I couldn't repro this on Windows 10 home, on the latest Chrome, Firefox, or Edge.

But... I discovered #42 in the process.

**Comment by BeigeBadger** [comment]
Hmmm weird... maybe  it's because I'm opening the index.html page through the file:// protocol.

**Comment by shakeelmohamed** [comment]
Ah, I usually do development on my Mac so I haven't noticed this before.
I'm going to close this since it's only a development related issue.

Really weird stuff happens locally in Windows 10 home on Chrome...
![capture](https://cloud.githubusercontent.com/assets/1480063/10413342/5ce0d0b4-6f5a-11e5-9649-a78fdf2c30f1.PNG)
