### ISSUE TITLE
Fix code scanning alert - Client-side cross-site scripting

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#420]
Tracking issue for:
- [ ] https://github.com/zen-audio-player/zen-audio-player.github.io/security/code-scanning/3

**Comment by ChandraShekharAgrawal** [comment]
Hi @shakeelmohamed , this link seems broken as well link in issue #421 . Please let me know if I'm missing something.

**Comment by shakeelmohamed** [comment]
@ChandraShekharAgrawal thanks for the note, see the screenshot below

<img width="948" alt="Screenshot 2023-09-22 at 1 38 46 PM" src="https://github.com/zen-audio-player/zen-audio-player.github.io/assets/1480063/ff124bd0-6e98-416a-95ac-bc1694d98dd9">

**Comment by ChandraShekharAgrawal** [comment]
@shakeelmohamed I have got this project up and running. I would like to work on this issue. Can you please assign this issue to me?
