### ISSUE TITLE
Search Suggestions Cursor

### ISSUE THREAD

**Issue by yasirw212** [zen-audio-player/zen-audio-player.github.io#430]
**Currently there is a text cursor normally used when hovering input fields that appears when hovering over the clickable search suggestions. I would like to swap this out for a hand cursor.**

**Reasons Why**

1. **User Expectation**: Users have come to associate the hand cursor with interactivity. When they see a hand cursor, they instinctively understand that an element is clickable or interactive. This helps in creating a more intuitive and user-friendly experience.

2. **Accessibility**: For users with disabilities, especially those who rely on screen readers or have difficulty with fine motor control, the hand cursor can provide an additional visual cue that an element is interactive. This supports a more inclusive and accessible design.

3. **Web Standards**: Following web design conventions and standards is essential for creating a user-friendly interface. The use of a hand cursor aligns with these standards, making the website design more familiar and predictable for users.

**Quick Fix**

In the styles.css file on the .tt-suggestion class:
>.tt-suggestion:{
     cursor: pointer
}

I would like to be assigned this issue if you agree with my reasoning and implement this into the project.

**Comment by shakeelmohamed** [comment]
Hi @yasirw212, thanks for the issue. On principle I agree with your code change, however youtube.com itself uses the `default` cursor for their search suggestion. 

My intention with this project has been to be as little design as possible. For that reason, I will close the issue but feel free to comment or re-open the discussion.
