### ISSUE TITLE
Migrate away from Bower

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#432]
Bower has been deprecated for years, we should rip it out at some point.

They have a guide on how we might do so: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

**Comment by voidCounter** [comment]
I'll work on that.

**Comment by shakeelmohamed** [comment]
@voidCounter fantastic, assigned to you. Let me know if you have any questions

**Comment by voidCounter** [comment]
@shakeelmohamed  Thanks. We have two options: move to npm or Yarn. Which one do you suggest to do so? From some reading, it looks like mixing both of them could create some issues as the project is already using npm.

**Comment by shakeelmohamed** [comment]
@voidCounter I prefer npm. I’d like to see a PR replacing our bower dependencies with [UNPKG](https://www.unpkg.com/) includes. That seems like the simplest solution and we benefit from not needing to check-in dependencies (i.e. our `bower_components` folder disappears).
