### ISSUE TITLE
Add browser compatibility matrix

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#48]
* ~~First version could be generating it manually using [browser-badge](https://github.com/substack/browser-badge)~~ This is very broken, look at what it generated using their example matrix!
![foo](https://cloud.githubusercontent.com/assets/1480063/11205268/3a2f4824-8cbb-11e5-80b5-167d89bfe181.png)

* Second version could be writing tests ~~using [Testling](https://ci.testling.com/) for true CI, which addresses~~ [testling is dead](https://github.com/substack/testling/issues/111), we need another solution here to address #6 also

Current known matrix:

- Best functionality
  - Chrome: Mac, Windows
  - Firefox: Mac, Windows
  - IE/Edge: Windows
- Janky functionality
  - Chrome: Android
  - Safari: Mac, iOS

**Comment by shakeelmohamed** [comment]
Semi-related, I kicked off a browswershots run which is taking screenshots of the site loaded up in a very broad matrix of browsers! The results are slowly pouring in here: http://browsershots.org/http://zen-audio-player.github.io/

**Comment by divayprakash** [comment]
Would an addition to the `README.md` work for this?

**Comment by divayprakash** [comment]
Something similar to 'browser badge' as you mentioned in a separate section at the end of the `README.md`

**Comment by shakeelmohamed** [comment]
@divayprakash yeah `.github/README.md` would be great, as part of #5 we might do something on the website as well
