### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#49]
We basically have 0 docs right now, a wiki would be nice :smile: 
Maybe we even make a separate repo just for docs? Then we can have zen-audio-player.github.io/docs be a valid URL

**Comment by shakeelmohamed** [comment]
Created a wiki, and added a Use Cases page as a start - hopefully more research will lead to more insight!

**Comment by shakeelmohamed** [comment]
Some general topics that would be helpful:

- How to get started quickly as a newbie
- How to test things locally (WAMP, MAMP, XAMPP) vs. opening the `index.html` file in a browser
- How to write tests
- What are our code conventions/style? (a `.jshintrc` would help a bunch here)
- How to install dependencies (frontend & test)
- How to run tests
- What to look for in a success/failed work session

**Comment by BeigeBadger** [comment]
I'm happy to write the part on testing things locally. I may get some time this weekend - I'm pushing a site live tomorrow for a client (outside of my day job) so I've been out of action all this week. =\

**Comment by shakeelmohamed** [comment]
Rock on @BeigeBadger!

**Comment by josectello** [comment]
What's the progress on this so far? Ironically, I'm a newbie (at Zen Audio Player) and I'm looking for an approachable issue to tackle. I was wondering if docs would be a good place to start. :)

**Comment by shakeelmohamed** [comment]
Welcome @josectello! Beyond `README.md` and `CONTRIBUTING.md`, there's a few loose ends on [the wiki](https://github.com/zen-audio-player/zen-audio-player.github.io/wiki/Contribution-flow). See if you can add a new page there just to test it, I may need to give you permissions

**Comment by josectello** [comment]
Thanks @shakeelmohamed. I went ahead and made a minor change to the front page of the wiki (mainly formatting), let me know if that looks alright!

As for `CONTRIBUTING.md`, is that something you guys would want to have in the repo? If so, I can fork and begin drafting something that expands more on contributions than the `Contributions` page of the wiki.

**Comment by shakeelmohamed** [comment]
Thanks @josectello, glad you have permissions - I've added you to the org!

We actually need the `CONTRIBUTING.md` file to show the banner you see when creating a new issue or pull request. We might want to reduce the contents of the file and move some content to the wiki, I think the length of the file may be intimidating to new users. What do you think about that?

**Comment by josectello** [comment]
I think I got it. So we want a quick start guide with maybe some screenshots of submitting a PR/issue for clarity to new users. Yeah I think that's a great idea. 

Just making sure, there isn't currently a `CONTRIBUTING.md`, right? I looked through and didn't appear to find one.

**Comment by shakeelmohamed** [comment]
@josectello it's actually in the `.github` directory, I forgot we moved it

**Comment by josectello** [comment]
@shakeelmohamed Thanks, I'll get started on that this Monday.

**Comment by josectello** [comment]
Work has been keeping me very busy for the past few days. Hopefully I will begin to work on this tomorrow.

**Comment by shakeelmohamed** [comment]
No worries @josectello

**Comment by shakeelmohamed** [comment]
@josectello Do you want to triage the the comments/description in this issue? I'd like to see 2 lists, todo & done.

**Comment by josectello** [comment]
@shakeelmohamed I was just thinking the other day a list would be great. I'm away this weekend, but I'll hop on that Monday evening!

**Comment by shakeelmohamed** [comment]
@josectello perfect, thanks a ton!

**Comment by josectello** [comment]
@shakeelmohamed Would it be easier to open up a new issue with a list of tasks that can be ticked off in markdown? I don't think I can edit any comments/descriptions on here except my own.

**Comment by shakeelmohamed** [comment]
@josectello yep that would be perfect

**Comment by shakeelmohamed** [comment]
Closing in favor of #201, which is more organized thanks to @josectello
