### ISSUE TITLE
Display unsupported message for non-Android mobile users

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#5]
TODO:

- [x] Try to get the best possible functionality on Android, autoplay will not work, by design.
- [ ] On iOS, and other mobile user agents display a message saying we don't support mobile browsers - since iOS will show videos in full screen, by design. see comments in #38 

Major bugs on Android

![screenshot_2015-05-11-07-57-32](https://cloud.githubusercontent.com/assets/1480063/7579916/1c949fb0-f820-11e4-84fd-e6a392f109e1.png)
![screenshot_2015-05-11-07-57-44](https://cloud.githubusercontent.com/assets/1480063/7579915/1c9479b8-f820-11e4-909c-012fe3ca1602.png)

**Comment by shakeelmohamed** [comment]
The changes for #33 made in #34 make this almost work on Android!

Steps:

0. Tap the demo link
0. Tap show player
0. Tap pause/play
0. Tap hide player
0. Tap pause play
0. Listen!



![nbph7nsgzzhoyab1lnxkgqusvhcmzax0degsnttdniq](https://cloud.githubusercontent.com/assets/1480063/9835414/a03e05ce-599e-11e5-997e-e08c1ea4c3b9.png)

**Comment by BlinkBP** [comment]
I made some mess with those commits. Sorry, I'm figuring Github out.
The app works fine on my Android smartphone (Chrome on Android 5.0.2).
I am not able to look into iOS issues though because I do not own any Apple product. I read [here](http://stackoverflow.com/questions/16513620/youtube-api-not-working-in-ios-iphone-ipad-but-working-fine-in-desktop-browser) that it may be possible to play videos on iOS the way we would like to though.

**Comment by shakeelmohamed** [comment]
@BlinkBP Just confirmed that it works on Android with your fix, but the player will pause when switching apps. For iOS, I'm content with saying we don't support it. The iOS specific API is very aggressive and forces a full screen player, we can't workaround this unless we make an iOS app.

![](https://cloud.githubusercontent.com/assets/1480063/10120326/709c123a-646a-11e5-9b62-1ee058a72792.png)

**Comment by yoshrubin** [comment]
Easy fix for iOS message might be checking User-Agent then redirecting to a html page saying that there's no compability atm, also site didn't work on android 6.0 for me

**Comment by shakeelmohamed** [comment]
@yoshrubin I'm not surprised. I'm happy to say we don't support mobile at all for now. We can dynamically change the contents of `index.html`, I don't think it makes sense to do a redirect. About line 411 and beyond in `js/everything.js` is where the code change should be. A bonus would be logging a Keen event when we get a mobile session

**Comment by FleetAdmiral** [comment]
@shakeelmohamed Hey can i take up this issue?

**Comment by shakeelmohamed** [comment]
@FleetAdmiral please do! I've removed the "up for grabs" label

**Comment by FleetAdmiral** [comment]
@shakeelmohamed Alright , will get onto it!

**Comment by shakeelmohamed** [comment]
@FleetAdmiral hey, any status update? 😄

**Comment by FleetAdmiral** [comment]
@shakeelmohamed  Will be done by tonight.

**Comment by shakeelmohamed** [comment]
@FleetAdmiral excellent!
