### ISSUE TITLE
Retain current time through video on reload

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#50]
It sucks when you reload the page and the video/song starts over from the beginning. We can do this a few different ways: URL, cookies, or the super awesome HTML5 local storage API.

edit:

An implementation might look something like the following, but with functions doing the 2 tasks:

1. upsert the time in `window.sessionStorage`
2. restore the player time, via `player.seekTo()`

```diff
diff --git a/js/everything.js b/js/everything.js
index e273a1a..eedc2ab 100644
--- a/js/everything.js
+++ b/js/everything.js
@@ -173,6 +173,15 @@ function updatePlayerTime() {
     $("#currentTime").text(cleanTime(player.getCurrentTime()));
     // TODO: after the video loads, player.getDuration() may have changed +/- 1
     $("#totalTime").text(cleanTime(player.getDuration()));
+
+    /**
+     * Store the current video's time, every 100ms as defined by
+     * by the setInterval() timer in onPlayerReady().
+     */
+    var videoID = getCurrentVideoID();
+    if (window.sessionStorage && videoID) {
+        window.sessionStorage[videoID] = player.getCurrentTime();
+    }
 }
 
 // Lock for updating the volume
@@ -342,6 +351,11 @@ $(function() {
     if (currentVideoID) {
         $("#v").attr("value", currentVideoID);
         getVideoDescription(currentVideoID);
+
+        if (window.sessionStorage && window.sessionStorage.hasOwnProperty(currentVideoID)) {
+            // TODO: verify that window.sessionStorage[currentVideoID] is an integer, else noop
+            player.seekTo(window.sessionStorage[currentVideoID]);
+        }
     }
 
     // Hide the demo link if playing the demo video's audio
```

**Comment by BeigeBadger** [comment]
I've been looking at the HTML5 local storage API and it looks pretty neat! Did we want to use local or session storage? I was leaning more towards session storage but though I'd better check with you first.

Info:

>HTML local storage provides two objects for storing data on the client:
>window.localStorage - stores data with no expiration date
>window.sessionStorage - stores data for one session (data is lost when the browser tab is closed)

I'm also happy to write a URL fallback for the older browsers that don't support the local storage API... maybe we could use modernizr if you didn't mind bloating the project some more.

**Comment by shakeelmohamed** [comment]
> Did we want to use local or session storage?

Right, session storage makes more sense in this case.

As for the older browsers, we don't need to worry about them IMO.
This is the matrix for [local storage](http://www.w3schools.com/HTML/html5_webstorage.asp) support & when it was added to the browsers:
![capturfiles_8](https://cloud.githubusercontent.com/assets/1480063/10862387/e88f01cc-7f62-11e5-87d3-0fd688234655.png)

Go for it @BeigeBadger! :clap:

**Comment by shakeelmohamed** [comment]
Added a theoretical implementation to the first comment :gem:
