### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#51]
Our current logo is... well it's just text and that's not an ideal logo, especially as a favicon.

I may do this myself, but I'm posting for visibility :eyes:

**Comment by IsaiahN** [comment]
Hello Shakeel, here are my attempts at the logo creation
![zenplayer11](https://cloud.githubusercontent.com/assets/14181435/11672945/de6dc1d0-9de2-11e5-8aa6-c5e36bd92c17.png)
![zenplayer10](https://cloud.githubusercontent.com/assets/14181435/11672943/de5f43f8-9de2-11e5-8ba6-577a241dd359.png)
![zenplayer9](https://cloud.githubusercontent.com/assets/14181435/11672944/de6496d2-9de2-11e5-93e0-9aa224267f5b.png)
![zenplayer8](https://cloud.githubusercontent.com/assets/14181435/11672947/de78c044-9de2-11e5-8e0f-08ddcb136898.png)
![zenplayer7](https://cloud.githubusercontent.com/assets/14181435/11672948/de7a751a-9de2-11e5-9ed5-ab413efb6534.png)
![zenplayer6](https://cloud.githubusercontent.com/assets/14181435/11672950/de831710-9de2-11e5-833e-88d7cdcf943d.png)
![zenplayer5](https://cloud.githubusercontent.com/assets/14181435/11672946/de776136-9de2-11e5-8950-fc1b3b0ac84d.png)
![zenplayer4](https://cloud.githubusercontent.com/assets/14181435/11672949/de80d0ae-9de2-11e5-9cb6-fe2607b85d01.png)
![zenplayer3](https://cloud.githubusercontent.com/assets/14181435/11672951/de887b38-9de2-11e5-9509-e60c1bc59d3c.png)
![zenplayer2](https://cloud.githubusercontent.com/assets/14181435/11672952/de8d3272-9de2-11e5-9f10-ac300f131c40.png)
![zenplayer](https://cloud.githubusercontent.com/assets/14181435/11672953/de946c5e-9de2-11e5-9042-6d543e47389c.png)

**Comment by shakeelmohamed** [comment]
Wow thanks @IsaiahN!

Of these, I like the following the best.
Can we use #4078c0 blue instead of the red, and remove the shadow on "ZEN"? Not sure if I like the background color yet, let's see those changes first :+1: 

![](https://cloud.githubusercontent.com/assets/14181435/11672943/de5f43f8-9de2-11e5-8ba6-577a241dd359.png)

**Comment by IsaiahN** [comment]
@shakeelmohamed - I've uploaded the changed version with a few variations (including the hue change):
![zenplayer23](https://cloud.githubusercontent.com/assets/14181435/11676258/c95414a4-9dfe-11e5-8f00-2fa8154f9eb7.png)
![zenplayer22](https://cloud.githubusercontent.com/assets/14181435/11676259/c955efc2-9dfe-11e5-992a-68855c2e0496.png)
![zenplayer21](https://cloud.githubusercontent.com/assets/14181435/11676260/c95e5a9a-9dfe-11e5-822a-bde997f8ee9d.png)
![zenplayer20](https://cloud.githubusercontent.com/assets/14181435/11676261/c9657adc-9dfe-11e5-8b45-0e3464d7664b.png)

**Comment by shakeelmohamed** [comment]
Great! I like the following the best.
@IsaiahN Can we see some renderings on different logo sizes? (ie: favicon, github org logo, homepage) I think we should be able to clearly identify it for any size, maybe that means subtracting pieces of the logo for smaller sizes.

![](https://cloud.githubusercontent.com/assets/14181435/11676259/c955efc2-9dfe-11e5-992a-68855c2e0496.png)

**Comment by IsaiahN** [comment]
https://makeappicon.com/upload/61544b1c755f43c58150f0ee05cf890f/android/drawable-xxxhdpi/ic_launcher.png

https://makeappicon.com/upload/61544b1c755f43c58150f0ee05cf890f/android/drawable-xxhdpi/ic_launcher.png

https://makeappicon.com/upload/61544b1c755f43c58150f0ee05cf890f/android/drawable-xhdpi/ic_launcher.png


![image](https://cloud.githubusercontent.com/assets/14181435/11732333/34aef75a-9f71-11e5-9636-f8f9e9b2dfc6.png)

http://makeappicon.com/upload/61544b1c755f43c58150f0ee05cf890f/android/drawable-hdpi/ic_launcher.png

Here are some lower res versions

**Comment by shakeelmohamed** [comment]
@IsaiahN I was afraid of this, the logo doesn't look great when it's smaller than ~200px wide. Can you work some magic here to make it look more recognizable when smaller?

**Comment by IsaiahN** [comment]
Here is the color update
![zenplayer34](https://cloud.githubusercontent.com/assets/14181435/11732676/81af72ca-9f74-11e5-8354-6b2c10133bbf.png)
![zenplayer33](https://cloud.githubusercontent.com/assets/14181435/11732677/81b82762-9f74-11e5-82b7-6776c3b1947e.png)
![zenplayer32](https://cloud.githubusercontent.com/assets/14181435/11732678/81be867a-9f74-11e5-816e-101706b623ee.png)
![zenplayer31](https://cloud.githubusercontent.com/assets/14181435/11732679/81c32608-9f74-11e5-9981-1fc8a8cb57b8.png)
![zenplayer30](https://cloud.githubusercontent.com/assets/14181435/11732680/81c882c4-9f74-11e5-9358-eb8337ab6fef.png)

**Comment by shakeelmohamed** [comment]
I'm liking this one the best

![](https://cloud.githubusercontent.com/assets/14181435/11732678/81be867a-9f74-11e5-816e-101706b623ee.png)

**Comment by IsaiahN** [comment]
Updated: 
![zenplayer35](https://cloud.githubusercontent.com/assets/14181435/11732985/9686af30-9f77-11e5-94da-bc402be897e1.png)

**Comment by shakeelmohamed** [comment]
By the time we're at a favicon, this is impossible to identify :frowning: 
![capturfiles_1](https://cloud.githubusercontent.com/assets/1480063/11733111/31b1b9aa-9f5f-11e5-924a-760232f75f77.png)

**Comment by IsaiahN** [comment]
@shakeel, right most icons are, which is why they are often One letter favicons Like the "Z" one

**Comment by IsaiahN** [comment]
And some variants....
![zenplayer40](https://cloud.githubusercontent.com/assets/14181435/11733448/6ef34fec-9f7b-11e5-835d-34f55c2ea4cd.png)
![zenplayer39](https://cloud.githubusercontent.com/assets/14181435/11733449/6f15e6e2-9f7b-11e5-82be-e95aab259335.png)
![zenplayer38](https://cloud.githubusercontent.com/assets/14181435/11733450/6f8c43dc-9f7b-11e5-8842-e7f0b276e5d5.png)
![zenplayer37](https://cloud.githubusercontent.com/assets/14181435/11733451/6f92be6a-9f7b-11e5-82a1-82f9d7c578da.png)

**Comment by shakeelmohamed** [comment]
Ah this is really nice, I think we can take this one in - at least for now!
@IsaiahN are you up for making a PR to update the files in the `img` directory?

![](https://cloud.githubusercontent.com/assets/14181435/11733451/6f92be6a-9f7b-11e5-82a1-82f9d7c578da.png)

**Comment by shakeelmohamed** [comment]
Closed by #75, kick ass job @IsaiahN!
