### ISSUE TITLE
Add a slider for time seek

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#55]
The only way to seek currently is to show the player and do it there. We already have a great slider for volume, we can steal most of that logic for this

**Comment by shakeelmohamed** [comment]
See #70 for a rough guideline of implementation

**Comment by shakeelmohamed** [comment]
How's this going @eirism? Just checking in, no need to panic :smirk_cat:

**Comment by eirism** [comment]
The dev/timeseek branch has a working implementatipn of it. The excact behaviour and placement/looks of it may need to be tweaked.

Den 29. desember 2015 10:14:56 CET, skrev Shakeel Mohamed <notifications@github.com>:

**Comment by shakeelmohamed** [comment]
Just tested this out, it works pretty well!

Leaving some notes here so I don't forget:

- [ ] Change the `setInterval()` interval to a lower value, maybe 50ms instead of the current 100ms
- [ ] The seek slider should be above the time display
- [ ] We should try to visually distinguish the 2 sliders. Maybe make the volume one smaller? Maybe make the seek slider 400px wide? Maybe move the video times to either side of the slider, something like quicktime

![](http://zapp5.staticworld.net/downloads/graphics/screenshots/1764f.jpg)

**Comment by shakeelmohamed** [comment]
More thoughts:

- Maybe the volume slider should be more vertical, like YouTube
<img width="252" alt="screen shot 2016-01-12 at 10 43 33 am" src="https://cloud.githubusercontent.com/assets/1480063/12273227/8870014c-b919-11e5-99e8-a230b8a560c8.png">
- Maybe the time seek slider should have a tooltip instead of having current time & duration on either side (leaving 00:00 / 00:01 where it is below the slider), see [example 8](http://seiyria.com/bootstrap-slider/)
<img width="121" alt="screen shot 2016-01-12 at 10 44 15 am" src="https://cloud.githubusercontent.com/assets/1480063/12273295/f9ceba18-b919-11e5-9bb7-df12b74ac58c.png">

**Comment by eirism** [comment]
We will need to install Bootstrap to use tooltips. For the volume slider, are you thinking of changing the circle for another icon? Sliders support unicode characters as handles, so if you find a suiting symbol we can use it.
Should the time tooltip be above or below the slider, and should it always be visible or only visible when hovering over/using it? Either way we will need to make space for the tooltip, so that it doesn't collide with the text around it.

**Comment by shakeelmohamed** [comment]
Oh right, let's not pull in another UI dependency :smile: 

> For the volume slider, are you thinking of changing the circle for another icon?

I played with the CSS a bit for the volume slider.
![capturfiles_20](https://cloud.githubusercontent.com/assets/1480063/12316406/065d84f4-ba3b-11e5-8133-3f768eaf4d16.png)
 Obviously the selector will need to be more specific, but I think this visually looks close enough to a vertical line
```css
.slider-handle {
    max-width: 3px;
}
```

> Should the time tooltip be above or below the slider, and should it always be visible or only visible when hovering over/using it?

Let's try above, you can add a `<br>` or two

**Comment by shakeelmohamed** [comment]
Done with #130
