### ISSUE TITLE
Migrate from jshint -> eslint

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#95]
We should be able to match our existing jshint configuration with [eslint](https://www.npmjs.com/package/eslint), which appears to be the better solution.

- [ ] update dependencies in `package.json`
- [ ] update the scripts in `package.json`
- [ ] update configuration wherever it lives
- [ ] remove the `.jshintrc` file, why did I ever check that in? :disappointed:

**Comment by agauniyal** [comment]
I'll be doing this + https://github.com/zen-audio-player/zen-audio-player.github.io/issues/112

**Comment by agauniyal** [comment]
http://eslint.org/docs/rules/ - which ones?

Or should I integrate and test with a sample conf and then you could add your .eslintrc yourself?

**Comment by shakeelmohamed** [comment]
Yeah let's start with a base config, if you can match the jshint settings in package.json that would be a great start

**Comment by agauniyal** [comment]
okay I will try to replicate with current .jshintrc. Also should I add this issue and #112 onto #114 PR or seperate PRs for each of them?

**Comment by shakeelmohamed** [comment]
Separate PRs please

**Comment by agauniyal** [comment]
@shakeelmohamed sorry for disturbing you, what does this line in scripts section of `package.json` does? `"lint:js": "jshint js test",`

**Comment by shakeelmohamed** [comment]
Right, it will only run `jshint` on the `/js` and `/test` directories. We don't want to bother running it against `bower_components` since that's library code
