### ISSUE TITLE
Hide #playerControls if not currently playing a video

### ISSUE THREAD

**Issue by shakeelmohamed** [zen-audio-player/zen-audio-player.github.io#97]
I don't know how I didn't notice this until now... we don't need to show the player controls at all unless we're playing a video.
For example: a when you first load up the page, you shouldn't see play/pause, show player, show description, or the volume controls because they're totally useless.

Solution:
- [ ] in `css/styles.css` add a new rule:
```css
#playerControls {
    display: none;
}
```
- [ ] in `js/everything.js` around line 365 under `if (currentVideoID) {` add
```javascript
$("#playerControls").show();
```

**Comment by Ab1d** [comment]
i will try this.
